FROM golang:1.26-bookworm AS builder
WORKDIR /src

COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY . .
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 go build -o /out/apid ./cmd/apid

FROM debian:12-slim AS runtime
WORKDIR /app
COPY --from=builder /out/apid ./apid
ENTRYPOINT ["./apid"]
CMD ["-c", "/etc/apid/apid.config.json"]
