FROM golang:1.25-bookworm AS builder
WORKDIR /src

COPY go.mod go.sum ./
RUN --mount=type=cache,target=/go/pkg/mod \
    go mod download

COPY . .
RUN --mount=type=cache,target=/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    CGO_ENABLED=0 go build -o /out/farc ./cmd/farc

FROM debian:12-slim AS runtime
WORKDIR /app
COPY --from=builder /out/farc ./farc
ENTRYPOINT ["./farc"]
CMD ["-c", "/etc/farc/farc.config.json"]
